client_id = 'admin-cli'
client_secret = ''
username = 'admin'
password = '<Password for Master Realm Admin>'
access_token_url = 'https://auth.aicoe.triveous.tech/realms/master/protocol/openid-connect/token'
fhir_base_url = 'https://fhir.aicoe.triveous.tech/fhir'
keycloak_url = 'https://auth.aicoe.triveous.tech/admin/realms/fhir'
access_token = None
product_access_token = 'example-pr̀̀oduct-access-token'